name: CI/CD Pipeline - DevOps

on:
  push:
    branches: [main, develop]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codigo
        uses: actions/checkout@v3

      - name: Login en Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build y Push imagen Docker
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/practica-devops:latest
            ${{ secrets.DOCKER_USERNAME }}/practica-devops:${{ github.sha }}

      - name: Imagen enviada
        run: echo "Imagen Docker enviada a Docker Hub"